name: "Setup Firebase Emulator (Windows Service)"
description: "Sets up Firebase Emulator Suite as a Windows service using NSSM for reliable background execution"
author: "C5T8fBt-WY"

branding:
  icon: "server"
  color: "orange"

inputs:
  firebase-tools-version:
    description: "Firebase Tools version to install"
    required: false
    default: "13.24.1"

  java-version:
    description: "Java version to setup (Temurin). Set to 'none' to use existing environment."
    required: false
    default: "17"

  project-id:
    description: "Firebase project ID for emulator"
    required: false
    default: "demo-project"

  firebase-config-path:
    description: "Path to firebase.json (absolute, workspace-relative with ./ prefix, or working-directory-relative)"
    required: false
    default: "./firebase.json"

  working-directory:
    description: "Working directory containing firebase.json and related files (firestore.rules, storage.rules, functions/, etc.)"
    required: false
    default: "."

  emulators:
    description: "Comma-separated list of emulators to start (e.g., auth,firestore,storage,functions). If empty, starts all configured in firebase.json"
    required: false
    default: ""

  wait-time:
    description: "Seconds to wait after starting service before health checks"
    required: false
    default: "60"

  skip-health-check:
    description: "Skip health check verification (not recommended)"
    required: false
    default: "false"

outputs:
  service-status:
    description: "Status of the Firebase Emulator service"
    value: ${{ steps.check-service.outputs.status }}

  health-check-summary:
    description: "JSON summary of health check results"
    value: ${{ steps.health-check.outputs.summary }}

runs:
  using: "composite"
  steps:
    - name: Validate Windows Runner
      shell: pwsh
      run: |
        if ($env:RUNNER_OS -ne 'Windows') {
          Write-Error "This action only supports Windows runners"
          exit 1
        }
        Write-Host "[OK] Running on Windows: $env:RUNNER_OS" -ForegroundColor Green

    - name: Setup Java
      if: inputs.java-version != 'none'
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java-version }}

    - name: Verify Java Installation
      if: inputs.java-version != 'none'
      shell: pwsh
      run: |
        $javaVersion = java -version 2>&1 | Select-Object -First 1
        Write-Host "[OK] Java installed: $javaVersion" -ForegroundColor Green

    - name: Setup Firebase Binary Directory
      shell: pwsh
      run: |
        $binaryPath = Join-Path $HOME ".firebase-binary"
        echo "FIREBASE_BINARY_PATH=$binaryPath" >> $env:GITHUB_ENV
        New-Item -ItemType Directory -Force -Path $binaryPath | Out-Null
        Write-Host "Binary path set to: $binaryPath" -ForegroundColor Cyan

    - name: Download Firebase CLI Standalone Binary
      shell: pwsh
      run: |
        Write-Host "Downloading Firebase CLI standalone binary v${{ inputs.firebase-tools-version }}..." -ForegroundColor Cyan

        $version = "${{ inputs.firebase-tools-version }}"
        $binaryPath = "${{ env.FIREBASE_BINARY_PATH }}"
        $exePath = Join-Path $binaryPath "firebase.exe"

        # Download from GitHub releases (specific version or latest)
        if ($version -eq "latest" -or $version -eq "") {
          $downloadUrl = "https://firebase.tools/bin/win/latest"
        } else {
          $downloadUrl = "https://github.com/firebase/firebase-tools/releases/download/v$version/firebase-tools-win.exe"
        }

        Write-Host "Downloading from: $downloadUrl" -ForegroundColor Gray

        try {
          Invoke-WebRequest -Uri $downloadUrl -OutFile $exePath -UseBasicParsing
          Write-Host "[OK] Binary downloaded successfully" -ForegroundColor Green
        } catch {
          Write-Host "[WARN] Failed to download specific version, falling back to latest" -ForegroundColor Yellow
          $downloadUrl = "https://firebase.tools/bin/win/latest"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $exePath -UseBasicParsing
        }

    - name: Add Firebase Binary to PATH
      shell: pwsh
      run: |
        $binPath = "${{ env.FIREBASE_BINARY_PATH }}"
        echo "$binPath" >> $env:GITHUB_PATH
        Write-Host "Added $binPath to PATH" -ForegroundColor Cyan

    - name: Verify Firebase CLI
      shell: pwsh
      run: |
        $exePath = Join-Path "${{ env.FIREBASE_BINARY_PATH }}" "firebase.exe"
        if (Test-Path $exePath) {
          $version = & $exePath --version
          Write-Host "[OK] Firebase CLI version: $version" -ForegroundColor Green
        } else {
          Write-Error "Firebase binary not found at $exePath"
          exit 1
        }

    - name: Install Firebase Functions dependencies
      shell: pwsh
      run: |
        $workDir = "${{ inputs.working-directory }}"
        $functionsPath = Join-Path $workDir "functions\package.json"

        if (Test-Path $functionsPath) {
          Write-Host "Installing Firebase Functions dependencies..." -ForegroundColor Cyan
          cd (Join-Path $workDir "functions")
          npm install
          Write-Host "[OK] Functions dependencies installed" -ForegroundColor Green
        } else {
          Write-Host "[INFO] No functions/package.json found in working directory, skipping..." -ForegroundColor Yellow
        }

    - name: Install NSSM
      shell: pwsh
      run: |
        Write-Host "Installing NSSM (Non-Sucking Service Manager)..." -ForegroundColor Cyan
        choco install nssm -y
        Write-Host "[OK] NSSM installed" -ForegroundColor Green

    - name: Start Firebase Emulators as Windows Service
      id: start-service
      shell: pwsh
      run: |
        Write-Host "======================================" -ForegroundColor Cyan
        Write-Host "Starting Firebase Emulator Service" -ForegroundColor Cyan
        Write-Host "======================================" -ForegroundColor Cyan
        Write-Host ""

        # Locate Firebase CLI binary
        $firebaseBin = Join-Path "${{ env.FIREBASE_BINARY_PATH }}" "firebase.exe"
        if (-not (Test-Path $firebaseBin)) {
          Write-Error "Could not find firebase.exe at $firebaseBin"
          exit 1
        }

        Write-Host "Firebase binary: $firebaseBin" -ForegroundColor Gray

        # Resolve working directory (absolute path)
        $workingDir = "${{ inputs.working-directory }}"
        if (-not [System.IO.Path]::IsPathRooted($workingDir)) {
          $workingDir = Join-Path $PWD.Path $workingDir
        }
        $workingDir = $workingDir -replace '\\$', ''  # Remove trailing slash

        if (-not (Test-Path $workingDir)) {
          Write-Error "Working directory not found: $workingDir"
          exit 1
        }

        $projectId = "${{ inputs.project-id }}"
        $emulatorsInput = "${{ inputs.emulators }}"
        $configPath = "${{ inputs.firebase-config-path }}"

        Write-Host "Working directory: $workingDir" -ForegroundColor Gray
        Write-Host "Firebase config: $configPath" -ForegroundColor Gray
        Write-Host "Project ID: $projectId" -ForegroundColor Cyan

        # Build emulator command arguments
        $argList = @("emulators:start", "--project=$projectId")

        # Add --config if using non-default firebase.json path
        if ($configPath -ne "./firebase.json") {
          $argList += "--config=$configPath"
          Write-Host "Using custom config: $configPath" -ForegroundColor Cyan
        }

        if ($emulatorsInput) {
          $argList += "--only"
          $argList += $emulatorsInput
          Write-Host "Starting specific emulators: $emulatorsInput" -ForegroundColor Cyan
        } else {
          Write-Host "Starting all configured emulators" -ForegroundColor Cyan
        }
        Write-Host ""

        # Install and configure Windows service using binary
        Write-Host "Installing service with Firebase binary..." -ForegroundColor Gray
        nssm install FirebaseEmulator $firebaseBin $argList

        nssm set FirebaseEmulator AppDirectory $workingDir
        nssm set FirebaseEmulator AppStdout "$workingDir\emulator-stdout.log"
        nssm set FirebaseEmulator AppStderr "$workingDir\emulator-stderr.log"

        # Start the service
        Write-Host "Starting service..." -ForegroundColor Yellow
        nssm start FirebaseEmulator

        Write-Host "[OK] Service start command issued" -ForegroundColor Green
        Write-Host ""

    - name: Wait for Service Initialization
      shell: pwsh
      run: |
        $waitTime = [int]"${{ inputs.wait-time }}"
        Write-Host "Waiting $waitTime seconds for emulators to initialize..." -ForegroundColor Yellow
        Start-Sleep -Seconds $waitTime
        Write-Host "[OK] Wait complete" -ForegroundColor Green

    - name: Check Service Status
      id: check-service
      shell: pwsh
      run: |
        $service = Get-Service -Name FirebaseEmulator -ErrorAction SilentlyContinue
        if ($service) {
          $status = $service.Status
          Write-Host "Service status: $status" -ForegroundColor $(if ($status -eq 'Running') { 'Green' } else { 'Yellow' })
          "status=$status" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
          Write-Host "[WARN] Service not found" -ForegroundColor Yellow
          "status=NotFound" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }

    - name: Health Check
      id: health-check
      if: inputs.skip-health-check != 'true'
      shell: pwsh
      run: |
        Write-Host "======================================" -ForegroundColor Cyan
        Write-Host "Emulator Health Check (via Hub)" -ForegroundColor Cyan
        Write-Host "======================================" -ForegroundColor Cyan
        Write-Host ""

        # Get Hub port from firebase.json (default 4400)
        # Handle config path resolution: absolute, workspace-relative (./ prefix), or working-directory-relative
        $configPath = "${{ inputs.firebase-config-path }}"
        if (-not [System.IO.Path]::IsPathRooted($configPath)) {
          if ($configPath.StartsWith("./") -or $configPath.StartsWith(".\")) {
            # Workspace-relative path (starts with ./)
            $configPath = Join-Path $PWD.Path $configPath
          } else {
            # Working-directory-relative path
            $workDir = "${{ inputs.working-directory }}"
            if (-not [System.IO.Path]::IsPathRooted($workDir)) {
              $workDir = Join-Path $PWD.Path $workDir
            }
            $configPath = Join-Path $workDir $configPath
          }
        }
        $hubPort = 4400

        if (Test-Path $configPath) {
          $config = Get-Content $configPath | ConvertFrom-Json
          if ($config.emulators.hub) {
            $hubPort = $config.emulators.hub.port
          }
          Write-Host "Using firebase.json from: $configPath" -ForegroundColor Gray
        } else {
          Write-Host "[WARN] firebase.json not found at $configPath, using default Hub port" -ForegroundColor Yellow
        }

        Write-Host "Checking Emulator Hub at port $hubPort..." -ForegroundColor Cyan
        Write-Host ""

        # Query Hub endpoint
        try {
          $hubResponse = Invoke-RestMethod -Uri "http://127.0.0.1:$hubPort/emulators" -TimeoutSec 5 -UseBasicParsing
          Write-Host "[OK] Emulator Hub is responding" -ForegroundColor Green
          Write-Host ""

          $results = @()
          foreach ($emulator in $hubResponse.PSObject.Properties) {
            $name = $emulator.Name
            $info = $emulator.Value
            
            $emulatorHost = if ($info.host) { $info.host } else { "127.0.0.1" }
            $port = $info.port
            
            Write-Host "$name Emulator:" -ForegroundColor Yellow
            Write-Host "  Host: $emulatorHost" -ForegroundColor Gray
            Write-Host "  Port: $port" -ForegroundColor Gray
            
            # Test port connectivity
            $portOpen = Test-NetConnection -ComputerName $emulatorHost -Port $port -InformationLevel Quiet -WarningAction SilentlyContinue
            Write-Host "  Status: $(if ($portOpen) { '[OK] Running' } else { '[WARN] Not accessible' })" -ForegroundColor $(if ($portOpen) { 'Green' } else { 'Yellow' })
            Write-Host ""
            
            $results += [PSCustomObject]@{
              Name = $name
              Host = $emulatorHost
              Port = $port
              Running = $portOpen
            }
          }

          # Summary
          Write-Host "======================================" -ForegroundColor Cyan
          Write-Host "Summary" -ForegroundColor Cyan
          Write-Host "======================================" -ForegroundColor Cyan
          $results | Format-Table -AutoSize

          $runningCount = ($results | Where-Object { $_.Running }).Count
          $totalCount = $results.Count
          
          if ($runningCount -eq $totalCount) {
            Write-Host "[SUCCESS] All $totalCount emulator(s) are running!" -ForegroundColor Green
          } else {
            Write-Host "[WARNING] $runningCount/$totalCount emulator(s) accessible" -ForegroundColor Yellow
          }

          # Export summary as JSON
          $summary = $results | ConvertTo-Json -Compress
          "summary=$summary" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

        } catch {
          Write-Host "[ERROR] Failed to connect to Emulator Hub on port $hubPort" -ForegroundColor Red
          Write-Host "Error: $_" -ForegroundColor Red
          Write-Host ""
          Write-Host "This may indicate emulators failed to start." -ForegroundColor Yellow
          Write-Host "Check emulator-stdout.log and emulator-stderr.log for details." -ForegroundColor Yellow
          exit 1
        }
